webdb/urls.py
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from .views import itemlist, details, create, userprofile
from .apiviews import rateitem,addwatchlist

urlpatterns = [
    path("", itemlist, name="list"),
    path('details/<pk>', details, name='details'),
    path('create/', create, name='create'),
    path('api/rate/<pk>/<value>/',rateitem,name='rateitem'),
    path('api/addwatchlist/<pk>', addwatchlist, name='addwatchlist'),
    path('profile/', userprofile, name="userprofile"),

]

urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

webseries/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webdb.urls')),
]

webdb/models.py
from django.db import models
from django.contrib.auth.models import User

#genre_choice = [('Romance','Romance'),('Action','Action'),('Sci-Fi','Sci-Fi'),]
lang_choice = [('English','English'),('Hindi','Hindi'),('Bengali','Bengali')]
plat_choice = [('Youtube','Youtube'),('Netflix','Netflix'),('Hoichoi','Hoichoi')]


class GenreList(models.Model):
    choice = models.CharField(max_length=20)
    def __str__(self): return self.choice


class ItemModel(models.Model):
    title = models.CharField(max_length=160)
    description = models.TextField()
    cover = models.ImageField(upload_to="covers/")
    published = models.DateTimeField(auto_now_add=True)
    genre = models.ManyToManyField(GenreList)
    language = models.CharField(choices=lang_choice,max_length=20)
    platform = models.CharField(choices=plat_choice,max_length=10)
    link = models.URLField(default="https://notfound.com/notfound.html")
    rating = models.DecimalField(decimal_places=2,max_digits=4,default=0)
    ratingcount = models.IntegerField(default=0)
    def __str__(self): return self.title



class CommentModel(models.Model):
    item = models.ForeignKey(ItemModel, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=300)
    published = models.DateTimeField(auto_now_add=True)


class RatingModel(models.Model):
    item = models.ForeignKey(ItemModel,on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    rating = models.SmallIntegerField(default=0)


class WatchList(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    item = models.ForeignKey(ItemModel, on_delete=models.CASCADE)
    watched = models.BooleanField(default=False)

webdb/forms.py
from django import forms
from .models import ItemModel,plat_choice,lang_choice,GenreList


select = forms.Select(attrs={'class':'ui selection dropdown'})
multiselect = forms.SelectMultiple(attrs={'class':'ui selection dropdown'})

class CreateForm(forms.ModelForm):
    genre = forms.ModelMultipleChoiceField(GenreList.objects,widget=multiselect)
    platform = forms.ChoiceField(widget=select, choices=plat_choice)
    language = forms.ChoiceField(widget=select, choices=lang_choice)
    class Meta:
        model = ItemModel
        exclude = ['rating','ratingcount']

webdb/views.py
from django.shortcuts import render,HttpResponse
from .models import ItemModel,RatingModel
from .forms import CreateForm


def itemlist(request):
    queryset = ItemModel.objects.all().order_by("-pk")
    return render(request, 'webdb/list.html', {'queryset':queryset})


def details(request, pk):
    query = ItemModel.objects.get(pk=pk)
    return render(request, 'webdb/details.html', {'q':query})

def userprofile(request):
    return render(request,'webdb/userprofile.html')


def create(request):
    if request.method=='POST':
        form = CreateForm(request.POST,request.FILES)
        if form.is_valid():
            form.save()
            return HttpResponse("success")
    form = CreateForm()
    return render(request, 'webdb/create.html', {'form': form})

webdb/templates/webdb/create.html
{% extends 'webdb/master.html' %}

{% block content %}

<div class="ui container">
    <form class="ui form" action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {% for f in form %}
        <div class="field">
            <label for="{{f.name}}">{{f.label}}</label>
            {{f}}
        </div>
        {% endfor %}
        <button class="ui medium orange button" type="submit">Create</button>
    </form>
</div>

<script>
    $('select.dropdown').dropdown();
</script>

{% endblock %}

webdb/templates/webdb/details.html
{% extends 'webdb/master.html' %}


{% block content %}
<div class="ui hidden divider"></div>

<div class="ui stackable doubling equal width grid container">

<div class="ui four wide column">
    <div class="ui rounded bordered image segment">
        <img src="{{q.cover.url}}" alt="{{q.title}}">
    </div>
</div>

<div class="ui column">
    <h4 class="ui horizontal divider header">
    <i class="bar chart icon"></i>  Description
    </h4>
    
    <div class="ui large header">{{q.title}}
<p class="sub header"><i class="hashtag icon" style="margin: 0px;padding: 0px"></i>{%for g in q.genre.all%}{{g}}, {%endfor%}</p>
    </div>

    <table class="ui unstackable definition table">
        <tr>
            <td class="two wide column">Platfom</td>
            <td>{{q.platform}}</td>
        </tr>
        <tr>
            <td class="two wide column">Language</td>
            <td>{{q.language}}</td>
        </tr>
        <tr>
            <td class="two wide column">Released</td>
            <td>{{q.published}}</td>
        </tr>
        <tr>
            <td class="two wide column">Rating</td>
            <td>
                <div class="ui heart rating" data-rating="{{q.rating|stringformat:'d'}}" data-max-rating="10"></div>
                <span class="meta"> {{q.rating}}/10 ({{q.ratingcount}} users)</span>
            </td>
        </tr>
    </table>
    
    <button class="ui blue button" id="addwatchlist">Add To WatchList</button>

</div>

</div>

<!----description---->

<div class="ui container">
    <div class="ui horizontal divider">Plot</div>

    <p>{{q.description}}</p>

</div>

<div class="ui hidden divider"></div>

<script>
    $(".rating").rating({onRate: function(rating){
        console.log(rating)
        var url = "/api/rate/"+"{{q.pk}}"+"/"+rating
        console.log(url)
        $.getJSON(url)
    }
    });

    $('#addwatchlist').click(function(){
        var url = '{% url 'addwatchlist' q.pk %}'
        console.log(url)
        var o = $.getJSON(url)
        console.log(o.responseJSON)
        $('#addwatchlist').removeClass('blue')

    });
</script>

{% endblock %}

webdb/templates/webdb/list.html
{% extends 'webdb/master.html' %}

{% block content %}

<div class="ui hidden divider"></div>

<div class="ui container">
<form action="" method="get" class="ui large fluid action input">
  <input type="text" placeholder="Search Series Title or Genre .."> <button class="ui orange button">Search</button>
</form>
</div>

<div class="ui hidden divider"></div>

<div class="ui cards centered fluid container">
    {% for q in queryset %}
    <a class="card" href="{% url 'details' q.pk %}">
        <div class="ui medium image">
            <img src="{{q.cover.url}}">
        </div>
      <div class="content">
        <div class="header">{{q.title}}</div>
        <div class="meta">
          <span class="category">
            {%for g in q.genre.all %}
            {{g}}, 
            {% endfor %}
          </span>
        </div>
        <div class="description">
          <p>{{q.description | truncatechars:160}}</p>
        </div>
      </div>
      <div class="extra content">
          <p class="meta"><i class="terminal icon"></i>  Rated by {{q.ratingcount}} People</p>
      </div>
    </a>
    {% endfor %}
    
</div>

{% endblock %}

webdb/templates/webdb/master.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>WebSeries Database</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/semantic.min.css' %}">
</head>
<body>
    <div class="ui sticky teal inverted menu">
        <div class="item header"><a href="{%url 'list'%}">WEBseries</a></div>
        <div class="item"><a href="{%url 'userprofile'%}">Profile</a></div>
        <div class="item"><a href="{%url 'create' %}">Add Series</a></div>
        <div class="right menu">
        <div class="item">
            <div class="ui input icon">
                <input type="text" placeholder="Search here">
                <i class="search link icon"></i>
            </div>
        </div>
        <div class="right item"> <i class="user icon"></i> login</div>
        </div>
    </div>

    <script src="{% static 'css/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'css/semantic.min.js' %}"></script>
    {% block content %}
    {% endblock %}


    
</body>
</html>

webdb/templates/webdb/userprofile.html
{% extends 'webdb/master.html' %}

{% block content %}

<div class="ui container">
    <h1 class="ui header">{{request.user}}</h1>
    <div class="ui horizontal divider">WatchList</div>

<div class="ui stackable doubling six cards">

    {%for i in request.user.watchlist_set.all%}
<a href="{%url 'details' i.item.pk%}" class="ui card">
    <div class="ui image">
        <img src="{{i.item.cover.url}}">
    </div>
    <div class="ui content">
        <h2 class="meta">{{i.item}}</h2>
    </div>
    <div class="ui extra content">
        <button class="ui button teal">Mark As Watched</button>
    </div>
</a>



    {% endfor %}
</div>
</div>

{% endblock %}